language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jschweihs/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jschweihs/docker-react npm run test